// AUTO-GENERATED by scripts/gen_types.go — DO NOT EDIT
// Run `make gen` to regenerate
// See scripts/gen_types.go for generation details and regeneration entrypoint.
export type GenerationStatus = "pending" | "running" | "completed" | "failed";

export interface GeneratedFile {
	path: string;
	content: string;
}

export interface Generation {
	id: string;
	project_id: string;
	spec_id: string;
	pipeline_run_id: string;
	status: GenerationStatus;
	branch_name?: string;
	pr_number?: number | null;
	pr_url?: string;
	files?: GeneratedFile[];
	error?: string;
	created_at: string;
	completed_at?: string | null;
}

export type IntegrationKind = "webhook" | "slack" | "github" | "linear" | "intercom" | "hubspot" | "zendesk";

export interface Integration {
	id: string;
	project_id: string;
	kind: IntegrationKind;
	name: string;
	config?: Record<string, any>;
	created_at: string;
	updated_at: string;
}

export interface IntegrationResponse {
	id: string;
	project_id: string;
	kind: IntegrationKind;
	name: string;
	webhook_secret?: string;
	config?: Record<string, any>;
	created_at: string;
	updated_at: string;
}

export type OrgPlan = "starter" | "pro" | "enterprise";

export type OrgRole = "owner" | "admin" | "member" | "viewer";

export interface Organization {
	id: string;
	name: string;
	slug: string;
	plan: OrgPlan;
	created_at: string;
	updated_at: string;
}

export interface OrgMember {
	org_id: string;
	user_id: string;
	role: OrgRole;
	invited_at: string;
	joined_at?: string | null;
}

export type SignalSource = "gong" | "intercom" | "linear" | "github" | "slack" | "zendesk" | "hubspot" | "amplitude" | "mixpanel" | "csv" | "manual" | "webhook";

export type SignalType = "call_transcript" | "support_ticket" | "feature_request" | "bug_report" | "user_interview" | "survey_response" | "nps_comment" | "churn_reason" | "product_review" | "slack_message" | "github_issue" | "linear_issue" | "usage_anomaly" | "note" | "event" | "review";

export interface Signal {
	id: string;
	project_id: string;
	source: SignalSource;
	source_ref: string;
	type: SignalType;
	content: string;
	metadata: Record<string, unknown>;
	occurred_at: string;
	ingested_at: string;
	embedding?: number[];
}

export interface UserStory {
	role: string;
	want: string;
	so_that: string;
}

export interface Spec {
	id: string;
	candidate_id: string;
	project_id: string;
	version: number;
	problem_statement: string;
	proposed_solution: string;
	user_stories: UserStory[];
	acceptance_criteria: string[];
	out_of_scope: string[];
	ui_changes: string;
	data_model_changes: string;
	open_questions: string[];
	generated_by?: string | null;
	created_at: string;
}

export interface AuditEntry {
	id: string;
	org_id: string;
	actor_id: string;
	action: string;
	resource_type: string;
	resource_id: string;
	metadata?: Record<string, unknown>;
	created_at: string;
}

export type CopilotNoteTargetType = "candidate" | "signal_batch" | "spec" | "generation" | "synthesis";

export type CopilotNoteType = "review" | "risk" | "suggestion" | "insight";

export interface CopilotNote {
	id: string;
	project_id: string;
	target_type: CopilotNoteTargetType;
	target_id: string;
	note_type: CopilotNoteType;
	content: string;
	metadata?: Record<string, unknown>;
	dismissed: boolean;
	created_at: string;
}

export type PipelineRunStatus = "pending" | "running" | "completed" | "failed";

export type PipelineTaskStatus = "pending" | "running" | "completed" | "failed";

export type PipelineType = "ingest" | "synthesis" | "spec_gen" | "codegen" | "digest" | "copilot";

export interface PipelineRun {
	id: string;
	project_id: string;
	type: PipelineType;
	status: PipelineRunStatus;
	metadata?: Record<string, unknown>;
	started_at?: string | null;
	completed_at?: string | null;
	error?: string;
	created_at: string;
	tasks?: PipelineTask[];
}

export interface PipelineTask {
	id: string;
	pipeline_run_id: string;
	river_job_id?: number | null;
	name: string;
	status: PipelineTaskStatus;
	attempt: number;
	started_at?: string | null;
	completed_at?: string | null;
	duration_ms?: number;
	error?: string;
	sort_order: number;
}

export type ProjectFramework = "react" | "nextjs" | "vue" | "svelte" | "angular";

export type ProjectStyling = "tailwind" | "css" | "css_modules" | "styled_components" | "emotion";

export interface Project {
	id: string;
	org_id: string;
	name: string;
	github_repo: string;
	framework: ProjectFramework;
	styling: ProjectStyling;
	created_by: string;
	created_at: string;
}

export interface User {
	id: string;
	github_id: number;
	github_login: string;
	email: string;
	avatar_url: string;
	created_at: string;
}

export type CandidateStatus = "new" | "specced" | "in_progress" | "reviewing" | "accepted" | "rejected" | "backlogged" | "shipped";

export interface FeatureCandidate {
	id: string;
	project_id: string;
	title: string;
	problem_summary: string;
	status: CandidateStatus;
	score: number;
	signal_count: number;
	frequency_score: number;
	recency_score: number;
	segment_weight: number;
	churn_risk_score: number;
	cluster_id: string;
	synthesis_run_id?: string | null;
	created_at: string;
	updated_at: string;
}

export interface CandidateSignal {
	candidate_id: string;
	signal_id: string;
	similarity_score: number;
	is_representative: boolean;
}

